<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="NTINDSK1100564" name="Default test" tests="7" failures="1" timestamp="13 Nov 2019 05:45:42 GMT" time="41.249" errors="0">
  <testcase name="abc" time="0.359" classname="Misc.NSEIndia"/>
  <testcase name="aaa" time="9.539" classname="Misc.NSEIndia">
    <failure type="java.io.FileNotFoundException" message="C:\Users\dhanrajsingh.thakare\workspace\SeleniumChallenge\src\main\java\utilities\testData2.xlsx (The system cannot find the file specified)">
      <![CDATA[java.io.FileNotFoundException: C:\Users\dhanrajsingh.thakare\workspace\SeleniumChallenge\src\main\java\utilities\testData2.xlsx (The system cannot find the file specified)
	at java.io.FileInputStream.open0(Native Method)
	at java.io.FileInputStream.open(Unknown Source)
	at java.io.FileInputStream.<init>(Unknown Source)
	at java.io.FileInputStream.<init>(Unknown Source)
	at utilities.readExcel.addExcelSheet(readExcel.java:65)
	at Misc.NSEIndia.aaa(NSEIndia.java:41)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1198)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1123)
	at org.testng.TestNG.run(TestNG.java:1031)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)
]]>
    </failure>
  </testcase> <!-- aaa -->
  <testcase name="bbb" time="0.0" classname="Misc.NSEIndia"/>
  <testcase name="dataMultiple" time="6.213" classname="Misc.NSEIndia"/>
  <testcase name="dataMultiple" time="6.076" classname="Misc.NSEIndia"/>
  <testcase name="dataMultiple" time="6.183" classname="Misc.NSEIndia"/>
  <testcase name="dataMultiple" time="6.013" classname="Misc.NSEIndia"/>
</testsuite> <!-- Default test -->
